<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * AfacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfacturerRepository extends \Doctrine\ORM\EntityRepository
{
}
