<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * AlteruserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlteruserRepository extends \Doctrine\ORM\EntityRepository
{
}
