<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * ArtaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtaRepository extends \Doctrine\ORM\EntityRepository
{
}
