<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticlesenventeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesenventeRepository extends \Doctrine\ORM\EntityRepository
{
	public function listearticles($search, $nombreParPage, $page)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($search === 0)
		{
			$qb = $this->createQueryBuilder('a')		
			->orderBy('a.designation', 'ASC');	
			$qb->getQuery();	
		}
		else
		{
			$qb = $this->createQueryBuilder('a')
			->where('a.designation = :search')
			->orWhere('a.reffrs = :search')
			->setParameter('search', $search)
			->orderBy('a.designation', 'ASC');	
			$qb->getQuery();
		}

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
}
