<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
	public function showarticle($partenaires, $username)
	{// pour chaque partenaire sort 
	 // les articles correspondants
		$i=0;
		if(isset($partenaires) && !empty($partenaires))
		{
			foreach($partenaires as $part)
			{	
				$i++;
				$qb = $this->createQueryBuilder('a');
				$qb->where('a.auteur = :auteur1 OR a.sharepartenaire = :sharepartenaire OR a.transfereur = :transfereur2 OR a.auteur = :auteur2 OR a.transfereur = :transfereur')
					->setParameter('auteur1', $username)		
					->setParameter('sharepartenaire', '0')
					->setParameter('transfereur2', $part->getPartpotUsername())
					->setParameter('auteur2', $part->getPartpotUsername())
					->setParameter('transfereur', $username)				
					->orderBy('a.id', 'DESC');	
				$articleslist = $qb->getQuery()->getResult();
				${'articlesl'.$i} = $articleslist;

				$array_articles = $articlesl1;
				for($j=2;$j<$i;$j++)
				{
					if(!isset($array_articles))
					{
						$array_articles .= ','.$articlesl.$j;
					}

				}
				$articleslist2 = array_merge($array_articles);
				$articleslist3 = array_slice($articleslist2, 0, 20); ;
				
				return $articleslist3;
			}
		}
		else
		{
				$qb = $this->createQueryBuilder('a');
				$qb->where('a.auteur = :auteur OR a.transfereur = :transfereur OR a.sharepartenaire = :sharepartenaire' )
					->setParameter('auteur', $username)
					->setParameter('transfereur', $username)
					->setParameter('sharepartenaire', '0')
					->setMaxResults(20)	
					->orderBy('a.id', 'DESC');
				$articleslist2 = $qb->getQuery()->getResult();	
				return $articleslist2;
		}	
	}
}
