<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * BondepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BondepartRepository extends \Doctrine\ORM\EntityRepository
{
}
