<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * BonretourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonretourRepository extends \Doctrine\ORM\EntityRepository
{
}
