<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * BrappelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrappelsRepository extends EntityRepository
{
	public function searchbrappelsadmin($du, $au, $nombreParPage, $page, $user, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('r');
		$qb->where('r.date <= :au')
		->setParameter('au', $au)
		->andWhere('r.date >= :du')
		->setParameter('du', $du)
		->andWhere('r.rapTexte != :texte')
		->setParameter('texte', '');
		if($user != 'tous')
		{
			$qb->andWhere('r.user = :user')
			->setParameter('user', $user);
		}
		else
		{
			$qb->andWhere('r.entreprise = :usersociete')
			->setParameter('usersociete', $societe);
		}
		$qb->orderBy('r.date', 'DESC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}	
}
