<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * CaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaRepository extends \Doctrine\ORM\EntityRepository
{	
    public function before30capot($user, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.capot) as capot'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :prev30')
		   ->setParameter('prev30', $prev30);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }
	
    public function before30capotarray($user, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.capot) as capot'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :prev30')
		   ->setParameter('prev30', $prev30);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }
	
    public function before30careal($user, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.careal) as careal'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :prev30')
		   ->setParameter('prev30', $prev30);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }
	
    public function before30carealarray($user, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.careal) as careal'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :prev30')
		   ->setParameter('prev30', $prev30);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }
	
    public function before30caperdu($user, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.caperdu) as caperdu'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :prev30')
		   ->setParameter('prev30', $prev30);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }	
    public function before30caperduarray($user, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.caperdu) as caperdu'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :prev30')
		   ->setParameter('prev30', $prev30);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }
	
    public function last30ca($user, $today, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.capot) as capot', 'SUM(c.careal) as careal', 'SUM(c.caperdu) as caperdu', 'c.date'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :today')
		   ->andWhere('c.date > :prev30')
		   ->setParameter('today', $today)
		   ->setParameter('prev30', $prev30)
		   ->groupBy('c.date');
                 
        return $qb->getQuery()->getArrayResult();
    }
	
    public function last30caarray($user, $today, $prev30)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.capot) as capot', 'SUM(c.careal) as careal', 'SUM(c.caperdu) as caperdu', 'c.date'); 
        $qb->where('c.username = :username')
              ->setParameter('username', $user)
		   ->andWhere('c.date <= :today')
		   ->andWhere('c.date > :prev30')
		   ->setParameter('today', $today)
		   ->setParameter('prev30', $prev30)
		   ->groupBy('c.date');
                 
        return $qb->getQuery()->getArrayResult();
    }
}
