<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * ChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChantierRepository extends \Doctrine\ORM\EntityRepository
{	
    public function updateBoom($term)
    {
 		$qb = $this->createQueryBuilder('f');
		$qb->select('f.nom, f.cp');
		$qb->where('f.nom LIKE :nom')
		->setParameter('nom','%'.$term.'%')		
		->orderBy('f.nom', 'ASC');					

           $arrayAss = $qb->getQuery()
        ->getArrayResult();
 
		// Transformer le tableau associatif en un tableau standard
		$array = array();
		foreach ($arrayAss as $data) {
			$array['raison'] = $data['nom'];
		}
 
		return $array;
    }
}
