<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * ComposantsRoulotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantsRoulotteRepository extends \Doctrine\ORM\EntityRepository
{
}
