<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * DepensesmachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepensesmachineRepository extends \Doctrine\ORM\EntityRepository
{
}
