<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * DocaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocaRepository extends \Doctrine\ORM\EntityRepository
{
}
