<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * DonemailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonemailRepository extends \Doctrine\ORM\EntityRepository
{
	public function showinvitations($nombreParPage, $page, $user)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// Sélection des tags dans la table user
	
		// La construction de la requête
		$qb = $this->createQueryBuilder('d')
		->where('d.parrainpseudo = :parrainpseudo')
		->setParameter('parrainpseudo', $user)
		->andWhere('d.ficheid = :ficheid')
		->setParameter('ficheid', 0)
		->orderBy('d.id', 'DESC')
		->getQuery();
		
		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}
}
