<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * EchangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchangesRepository extends \Doctrine\ORM\EntityRepository
{
}
