<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * EventparcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventparcRepository extends \Doctrine\ORM\EntityRepository
{
}
