<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * EventsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsiteRepository extends \Doctrine\ORM\EntityRepository
{
}
