<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

	public function searchcr($du, $au, $nombreParPage, $page, $user, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('r');
		$qb->where('r.eventDate <= :au')
		->setParameter('au', $au)
		->andWhere('r.eventDate >= :du')
		->setParameter('du', $du);
		if($user != 'tous')
		{
			$qb->andWhere('r.user = :user')
			->setParameter('user', $user);
		}
		else
		{
			$qb->andWhere('r.entreprise = :usersociete')
			->setParameter('usersociete', $societe);
		}
		$qb->andWhere('r.cr = :cr')
		->setParameter('cr', 1)
		->orderBy('r.eventDate', 'ASC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}

	public function searchcradmin($du, $au, $nombreParPage, $page, $user, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('r');
		$qb->where('r.eventDate <= :au')
		->setParameter('au', $au)
		->andWhere('r.eventDate >= :du')
		->setParameter('du', $du)
		->andWhere('r.eventComment != :du')
		->setParameter('du', '');
		$qb->orderBy('r.eventDate', 'DESC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}	
}
