<?php

namespace Bacloo\CrmBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FactaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactaRepository extends \Doctrine\ORM\EntityRepository
{	
	public function searchfacta($du, $au, $clientid, $client, $reglement, $typedoc, $nombreParPage, $page)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.factures', 'c')
					->addSelect('c');
		$qb->where('f.controle = :controle')
		->setParameter('controle', 1234);

		if($du != 0 and $au != 0){
			$qb->andWhere('f.echeance >= :du');
			$qb->andWhere('f.echeance <= :au');
			$qb->setParameter('du', $du.'%');				
			$qb->setParameter('au', $au.'%');				
		}
		
		if($clientid != 0){
			$qb->andWhere('f.clientid >= :clientid');
			$qb->setParameter('clientid', $clientid.'%');			
		}
		
		if($client != 0){
			$qb->andWhere('f.client >= :client');
			$qb->setParameter('client', $client.'%');			
		}
		
		if($reglement != 0){
			$qb->andWhere('f.reglement >= :reglement');
			$qb->setParameter('reglement', $reglement.'%');			
		}
		
		if($typedoc != 0){
			$qb->andWhere('f.typedoc >= :typedoc');
			$qb->setParameter('typedoc', $typedoc.'%');			
		}				
		$qb->getQuery();		

		return $qb;
	}
}
