<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
	// public function searchfiche($ficheid, $raisonSociale, $nom)
	// {
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		// $qb = $this->createQueryBuilder('f')
					// ->leftJoin('f.bcontacts', 'c')
					// ->addSelect('c');
		// $qb->where('f.id = :id')
		// ->setParameter('id', $ficheid);
		// if(isset($raisonSociale) and isset($ficheid)){
			// $qb->andWhere('f.raisonSociale LIKE :raisonSociale');
		// }
		// elseif(isset($raisonSociale) and empty($ficheid))
		// {
			// $qb->orWhere('f.raisonSociale LIKE :raisonSociale');		
		// }
		// else
		// {
			// $qb->orWhere('f.raisonSociale = :raisonSociale');		
		// }		
		// $qb->setParameter('raisonSociale', '%'.$raisonSociale.'%');
		
		// if(isset($nom) and isset($raisonSociale)){
			// $qb->andWhere('c.nom LIKE :nom');
		// }
		// elseif(isset($nom) and empty($raisonSociale))
		// {
			// $qb->orWhere('c.nom LIKE :nom');		
		// }		
		// else
		// {
			// $qb->orWhere('c.nom = :nom');		
		// }		
		// $qb->setParameter('nom', '%'.$nom.'%');		
		// return $qb->getQuery()
		// ->getResult();
	// }

	public function searchrap($du, $au, $nombreParPage, $page, $user)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'r')
					->addSelect('r');
		$qb->where('r.date <= :au')
		->setParameter('au', $au)
		->andWhere('r.date >= :du')
		->setParameter('du', $du)
		->andWhere('r.user = :user')
		->setParameter('user', $user)
		->andWhere('r.afaire <> :afaire')
		->setParameter('afaire', '1')
		->andWhere('r.rdv <> :rdv')
		->setParameter('rdv', '1')
		->orderBy('r.date', 'ASC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
	
	public function searchallrap($du, $au, $nombreParPage, $page, $user)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'r')
					->addSelect('r');
		$qb->where('r.date <= :au')
		->setParameter('au', $au)
		->andWhere('r.date >= :du')
		->setParameter('du', $du)
		->andWhere('r.user = :user')
		->setParameter('user', $user)
		->orderBy('r.date', 'ASC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
	public function searcha_faire($du, $au, $nombreParPage, $page, $user)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'r')
					->addSelect('r');
		$qb->where('r.date <= :au')
		->setParameter('au', $au)
		->andWhere('r.date >= :du')
		->setParameter('du', $du)
		->andWhere('r.user = :user')
		->setParameter('user', $user)
		->andWhere('r.afaire = :afaire')
		->setParameter('afaire', '1')
		->orderBy('r.date', 'ASC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
	public function searchrdv($du, $au, $nombreParPage, $page, $user)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'r')
					->addSelect('r');
		$qb->where('r.date <= :au')
		->setParameter('au', $au)
		->andWhere('r.date >= :du')
		->setParameter('du', $du)
		->andWhere('r.user = :user')
		->setParameter('user', $user)
		->andWhere('r.rdv = :rdv')
		->setParameter('rdv', '1')
		->orderBy('r.date', 'ASC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}	

	public function searchfiche($raisonSociale, $view, $nom, $activite, $besoin, $nombreParPage, $page, $societe, $cp, $ville, $cperso1, $cperso2, $cperso3, $memo, $histo, $fonction, $besoinfilter, $rsfilter, $nomfilter, $activitefilter, $cpfilter, $villefilter, $cperso1filter, $cperso2filter, $cperso3filter, $memofilter, $histofilter, $fonctionfilter)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.bcontacts', 'c')
					->leftJoin('f.event', 'e')
					->leftJoin('f.memo', 'm')
					->addSelect('c')
					->addSelect('e')
					->addSelect('m');
		
		if($view == 'annuaire')
		{
			$qb->where('f.user = :user')
			->setParameter('user', 'bacloo');	
			$qb->andWhere('f.typefiche = :typefiche')
			->setParameter('typefiche', 'prospect');			
		}
		else
		{
			$qb->where('f.usersociete = :usersociete')
			->setParameter('usersociete', $societe);	
			$qb->andWhere('f.typefiche = :typefiche')
			->setParameter('typefiche', $view);		
		}

		if(isset($raisonSociale)){
			if(isset($rsfilter) && $rsfilter == 'commencepar')
			{
				$qb->andWhere('f.raisonSociale LIKE :raisonSociale');
					   $qb->setParameter('raisonSociale', $raisonSociale.'%');				
			}
			elseif(isset($rsfilter) && $rsfilter == 'contient')
			{
				$qb->andWhere('f.raisonSociale LIKE :raisonSociale');
					   $qb->setParameter('raisonSociale', '%'.$raisonSociale.'%');
			}
		}
		if(isset($nom)){
			if(isset($nomfilter) && $nomfilter == 'commencepar')
			{
				$qb->andWhere('c.nom LIKE :nom');
					   $qb->setParameter('nom', $nom.'%');				
			}
			elseif(isset($nomfilter) && $nomfilter == 'contient')
			{
				$qb->andWhere('c.nom LIKE :nom');
					   $qb->setParameter('nom', '%'.$nom.'%');
			}
		}
		if(isset($activite)){
			if(isset($activitefilter) && $activitefilter == 'commencepar')
			{
				$qb->andWhere('f.activite LIKE :activite');
					   $qb->setParameter('activite', $activite.'%');				
			}
			elseif(isset($activitefilter) && $activitefilter == 'contient')
			{
				$qb->andWhere('f.activite LIKE :activite');
					   $qb->setParameter('activite', '%'.$activite.'%');
			}
		}
		if(isset($besoin)){
			if(isset($besoinfilter) && $besoinfilter == 'commencepar')
			{
				$qb->andWhere('f.tags LIKE :besoin');
					   $qb->setParameter('besoin', $besoin.'%');				
			}
			elseif(isset($besoinfilter) && $besoinfilter == 'contient')
			{
				$qb->andWhere('f.tags LIKE :besoin');
					   $qb->setParameter('besoin', '%'.$besoin.'%');
			}
		}
		if(isset($cp)){
			if(isset($cpfilter) && $cpfilter == 'commencepar')
			{
				$qb->andWhere('f.cp LIKE :cp');
					   $qb->setParameter('cp', $cp.'%');				
			}
			elseif(isset($cpfilter) && $cpfilter == 'contient')
			{
				$qb->andWhere('f.cp LIKE :cp');
					   $qb->setParameter('cp', '%'.$cp.'%');
			}
			elseif(isset($cpfilter) && $cpfilter == 'superieur')
			{
				$qb->andWhere('f.cp > :cp');
					   $qb->setParameter('cp', $cp);
			}
			elseif(isset($cpfilter) && $cpfilter == 'inferieur')
			{
				$qb->andWhere('f.cp < :cp');
					   $qb->setParameter('cp', $cp);
			}
		}
		if(isset($ville)){
			if(isset($villefilter) && $villefilter == 'commencepar')
			{
				$qb->andWhere('f.ville LIKE :ville');
					   $qb->setParameter('ville', $ville.'%');				
			}
			elseif(isset($villefilter) && $villefilter == 'contient')
			{
				$qb->andWhere('f.ville LIKE :ville');
					   $qb->setParameter('ville', '%'.$ville.'%');
			}
		}
		if(isset($cperso1)){
			if(isset($cperso1filter) && $cperso1filter == 'commencepar')
			{
				$qb->andWhere('f.cperso1 LIKE :cperso1');
					   $qb->setParameter('cperso1', $cperso1.'%');				
			}
			elseif(isset($cperso1filter) && $cperso1filter == 'contient')
			{
				$qb->andWhere('f.cperso1 LIKE :cperso1');
					   $qb->setParameter('cperso1', '%'.$cperso1.'%');
			}
			elseif(isset($cperso1filter) && $cperso1filter == 'superieur')
			{
				$qb->andWhere('f.cperso1 > :cperso1');
					   $qb->setParameter('cperso1', $cperso1);
			}
			elseif(isset($cperso1filter) && $cperso1filter == 'inferieur')
			{
				$qb->andWhere('f.cperso1 < :cperso1');
					   $qb->setParameter('cperso1', $cperso1);
			}
		}
		if(isset($cperso2)){
			if(isset($cperso2filter) && $cperso2filter == 'commencepar')
			{
				$qb->andWhere('f.cperso2 LIKE :cperso2');
					   $qb->setParameter('cperso2', $cperso2.'%');				
			}
			elseif(isset($cperso2filter) && $cperso2filter == 'contient')
			{
				$qb->andWhere('f.cperso2 LIKE :cperso2');
					   $qb->setParameter('cperso2', '%'.$cperso2.'%');
			}
			elseif(isset($cperso2filter) && $cperso2filter == 'superieur')
			{
				$qb->andWhere('f.cperso2 > :cperso2');
					   $qb->setParameter('cperso2', $cperso2);
			}
			elseif(isset($cperso2filter) && $cperso2filter == 'inferieur')
			{
				$qb->andWhere('f.cperso2 < :cperso2');
					   $qb->setParameter('cperso2', $cperso2);
			}
		}
		if(isset($cperso3)){
			if(isset($cperso3filter) && $cperso3filter == 'commencepar')
			{
				$qb->andWhere('f.cperso3 LIKE :cperso3');
					   $qb->setParameter('cperso3', $cperso3.'%');				
			}
			elseif(isset($cperso3filter) && $cperso3filter == 'contient')
			{
				$qb->andWhere('f.cperso3 LIKE :cperso3');
					   $qb->setParameter('cperso3', '%'.$cperso3.'%');
			}
			elseif(isset($cperso3filter) && $cperso3filter == 'superieur')
			{
				$qb->andWhere('f.cperso3 > :cperso3');
					   $qb->setParameter('cperso3', $cperso3);
			}
			elseif(isset($cperso3filter) && $cperso3filter == 'inferieur')
			{
				$qb->andWhere('f.cperso3 < :cperso3');
					   $qb->setParameter('cperso3', $cperso3);
			}
		}
		if(isset($memo)){
			if(isset($memofilter) && $memofilter == 'commencepar')
			{
				$qb->andWhere('m.texte LIKE :texte');
					   $qb->setParameter('texte', $memo.'%');				
			}
			elseif(isset($memofilter) && $memofilter == 'contient')
			{
				$qb->andWhere('m.texte LIKE :texte');
					   $qb->setParameter('texte', '%'.$memo.'%');
			}
		}
		if(isset($histo)){
			if(isset($histofilter) && $histofilter == 'commencepar')
			{
				$qb->andWhere('e.eventComment LIKE :eventComment');
					   $qb->setParameter('eventComment', $histo.'%');				
			}
			elseif(isset($histofilter) && $histofilter == 'contient')
			{
				$qb->andWhere('e.eventComment LIKE :eventComment');
					   $qb->setParameter('eventComment', '%'.$histo.'%');
			}
		}
		if(isset($fonction)){
			if(isset($fonctionfilter) && $fonctionfilter == 'commencepar')
			{
				$qb->andWhere('c.fonction LIKE :fonction');
					   $qb->setParameter('fonction', $fonction.'%');				
			}
			elseif(isset($fonctionfilter) && $fonctionfilter == 'contient')
			{
				$qb->andWhere('c.fonction LIKE :fonction');
					   $qb->setParameter('fonction', '%'.$fonction.'%');
			}
		}				
		$qb->getQuery();		

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}
	
	public function searchfiche_init($nombreParPage, $page, $user)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f');
		$qb->where('f.user = :user')
		->setParameter('user', $user)		
		->orderBy('f.raisonSociale', 'ASC')					
		->getQuery();		

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}	

	public function searchfiche_init_client($nombreParPage, $page, $societe)
	{//$critere = array('bacloo', 'toto');
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f');
		$qb->where('f.usersociete = :usersociete')
		->andWhere('f.typefiche = :typefiche')
		->setParameter('usersociete', $societe)	
		->setParameter('typefiche', 'prospect')		
		->orderBy('f.raisonSociale', 'ASC')					
		->getQuery();
		
		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}
	

	
	public function searchfiche_init_fournisseur($nombreParPage, $page, $societe)
	{
		//On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		//La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f');
		$qb->where('f.usersociete = :usersociete')
		->andWhere('f.typefiche = :typefiche')
		->orWhere('f.typefiche = :typefiche2')
		->setParameter('usersociete', $societe)		
		->setParameter('typefiche', 'fournisseur')		
		->setParameter('typefiche2', 'loueur')		
		->orderBy('f.raisonSociale', 'ASC')					
		->getQuery();		

		//On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		//Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		//(n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}
	
	public function searchfiche_init_corbeille($nombreParPage, $page, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f');
		$qb->where('f.usersociete = :usersociete')
		->andWhere('f.typefiche = :typefiche')
		->setParameter('usersociete', $societe)	
		->setParameter('typefiche', 'corbeille')		
		->orderBy('f.raisonSociale', 'ASC')					
		->getQuery();		

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}
	
	public function searchfiche_init_shared($nombreParPage, $page, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f');
		$qb->where('c.usersociete = :usersociete')
		->setParameter('usersociete', $societe)		
		->orderBy('f.raisonSociale', 'ASC')					
		->getQuery();		

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}
	
	public function searchfiche_init_annuaire($nombreParPage, $page)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		// La construction de la requête reste inchangée
		$qb = $this->createQueryBuilder('f');
		$qb->where('f.user = :user')
		->setParameter('user', 'bacloo')		
		->orderBy('f.raisonSociale', 'ASC')					
		->getQuery();		

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);
	}

	public function count_shared_fiche($user)
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('COUNT(c.id) as nbshared');
		$qb->where('c.usersociete = :usersociete')
		->setParameter('usersociete', $user)		
		->orderBy('f.raisonSociale', 'ASC');					
		$count_shared = $qb->getQuery()->getSingleScalarResult();

		return $count_shared;
	}
	
	public function count_rappels($du, $au, $user)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'b')
					->addSelect('b');
		$qb->select('COUNT(b.id) as nbrappels');
		$qb->where('b.user = :user')
		->setParameter('user', $user)		
		->andWhere('b.date >= :du')
		->setParameter('du', $du)	
		->andWhere('b.date <= :au')
		->setParameter('au', $au)	
		->andWhere('b.afaire != :afaire')
		->setParameter('afaire', 1)
		->andWhere('b.rdv != :rdv')
		->setParameter('rdv', 1);					
		$count_rappels = $qb->getQuery()->getSingleScalarResult();

		return $count_rappels;
	}	
	
	public function count_rappelsarray($du, $au, array $user)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'b')
					->addSelect('b');
		$qb->select('COUNT(b.id) as nbrappels');
		$qb->where('b.user in (:user)')
		->setParameter('user', $user)		
		->andWhere('b.date >= :du')
		->setParameter('du', $du)	
		->andWhere('b.date <= :au')
		->setParameter('au', $au)	
		->andWhere('b.afaire = :afaire')
		->setParameter('afaire', '0')
		->andWhere('b.rdv = :rdv')
		->setParameter('rdv', '0');					
		$count_rappels = $qb->getQuery()->getSingleScalarResult();

		return $count_rappels;
	}	
	
	public function count_a_faire($du, $au, $user)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'b')
					->addSelect('b');
		$qb->select('COUNT(b.id) as nbrappels');
		$qb->where('b.user = :user')
		->setParameter('user', $user)		
		->andWhere('b.date >= :du')
		->setParameter('du', $du)	
		->andWhere('b.date <= :au')
		->setParameter('au', $au)	
		->andWhere('b.afaire = :afaire')
		->setParameter('afaire', '1');					
		$count_a_faire = $qb->getQuery()->getSingleScalarResult();

		return $count_a_faire;
	}	
	
	public function count_a_faire_array($du, $au, array $user)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'b')
					->addSelect('b');
		$qb->select('COUNT(b.id) as nbrappels');
		$qb->where('b.user in (:user)')
		->setParameter('user', $user)		
		->andWhere('b.date >= :du')
		->setParameter('du', $du)	
		->andWhere('b.date <= :au')
		->setParameter('au', $au)	
		->andWhere('b.afaire = :afaire')
		->setParameter('afaire', '1');					
		$count_a_faire = $qb->getQuery()->getSingleScalarResult();

		return $count_a_faire;
	}
	
	public function count_rdv($du, $au, $user)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'b')
					->addSelect('b');
		$qb->select('COUNT(b.id) as nbrappels');
		$qb->where('b.user = :user')
		->setParameter('user', $user)		
		->andWhere('b.date >= :du')
		->setParameter('du', $du)	
		->andWhere('b.date <= :au')
		->setParameter('au', $au)	
		->andWhere('b.rdv = :rdv')
		->setParameter('rdv', '1');					
		$count_rdv = $qb->getQuery()->getSingleScalarResult();

		return $count_rdv;
	}
	
	public function count_rdv_array($du, $au, array $user)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'b')
					->addSelect('b');
		$qb->select('COUNT(b.id) as nbrappels');
		$qb->where('b.user in (:user)')
		->setParameter('user', $user)		
		->andWhere('b.date >= :du')
		->setParameter('du', $du)	
		->andWhere('b.date <= :au')
		->setParameter('au', $au)	
		->andWhere('b.rdv = :rdv')
		->setParameter('rdv', '1');					
		$count_rdv = $qb->getQuery()->getSingleScalarResult();

		return $count_rdv;
	}
	
	public function showfiche($user, $id)
	{
		// Sélection des tags dans la table user
	
		// La construction de la requête
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.fos_user', 'c')
					->addSelect('c');		
		$qb->where('f.user = :user')
		->setParameter('user', $user)
		->andWhere('f.id = :id')
		->setParameter('id', $id);
		
		return $qb->getQuery()
				  ->getResult();
	}

	//Envoie le nombre de prospects potentiels	
	public function count_prospot($tags, $user)
	{
	$count_tags = 0;
		foreach($tags as $tag)
		{	
			$qb = $this->createQueryBuilder('f');
			$qb->select('COUNT(f.id) as nbtags');
			$qb->where('f.user != :user')
				->setParameter('user', $user);	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', 'x');	
			$qb->andwhere('f.tags LIKE :tags');
			$qb->setParameters(array('tags' => $tag.' ', 'tags' => $tag));
			$count_tag = $qb->getQuery()->getSingleScalarResult();
			$count_tags += $count_tag;
		}	
		return $count_tags;	
	}
	
	public function count_prospotlist($tags, $user)
	{// pour chaque tag de l'utilisateur connecté on sort 
	 // les fiches correspondantes qui constituent des prospects
		$i=0;
		foreach($tags as $tag)
		{	
			$i++;
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user != :user')
				->setParameter('user', $user);	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', 'x');		
			$qb->andwhere('f.tags LIKE :tags');
			$qb->setParameter('tags', $tag);
			$prospotlist = $qb->getQuery()->getResult();
			${'prospotl'.$i} = $prospotlist;

			$array_fiches = $prospotl1;
			for($j=2;$j<$i;$j++)
			{
				if(!isset($array_fiches))
				{
					$array_fiches .= ','.$prospotl.$j;
				}

			}
			$prospotlist = array_merge($array_fiches);
		}			
	return $prospotlist;	
	}
	
	public function majfichevend($tags, $user)
	{// pour chaque fiche de l'utilisateur connecté on voit 
	 // celles qui interressent les utilisateurs connectés. on obtient les fiches vendables.
		$i=0;
		foreach($tags as $tag)
		{	
			$i++;
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user = :user')
				->setParameter('user', $user);	
			$qb->andwhere('f.tags LIKE :tags');
			$qb->setParameter('tags', $tag);
			$fichesvendables = $qb->getQuery()->getResult();
			
			if($i == 1)
			{
				${'fichesvend'.$i} = $fichesvendables;
			}
			else
			{
			$j=$i-1;
				if(isset(${'fichesvend'.$j}))
				{
					$fichesvendables = array_merge(${'fichesvend'.$j},$fichesvendables);
				}
			}
		}
		$fichesvendablesok = $fichesvendables;
		return $fichesvendablesok;
	}	

	public function besoinsfiche($id)
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('f.tags')
		   ->where('f.id = :id')
		   ->setParameter('id', $id);
		return $besoins = $qb->getQuery()->getSingleScalarResult();
	}
	
	public function activitefiche($id)
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('f.activite')
		   ->where('f.id = :id')
		   ->setParameter('id', $id);
		return $activite = $qb->getQuery()->getSingleScalarResult();
	}
	
	public function prospotlist($tags, $actv, $user)
	{
	$i = 0;
	$count_tag = '';
	if($tags != 0)
	{
		foreach($tags as $tag)
		{	
			$i++;
			if($i == 1)
			{
				$qb = $this->createQueryBuilder('f');
				$qb->where('f.user != :user')
					->setParameters(array('user' => $user, 'user' => 'x'));	
				// $qb->andwhere('f.user != :user');
				// $qb->setParameter('user', 'x');		
				$qb->andwhere('f.tags LIKE :tags');
				$qb->setParameter('tags', '%'.$tag.'%');
				$qb->andwhere('f.copyof is NULL');
				$qb->setMaxResults(50);
				$count_ta = $qb->getQuery()->getResult();
				${'array_tags'.$i} = $count_ta;
			}
			else
			{
				$qb = $this->createQueryBuilder('f');
				$qb->where('f.user != :user')
					->setParameters(array('user' => $user, 'user' => 'x'));	
				// $qb->andwhere('f.user != :user');
				// $qb->setParameter('user', 'x');		
				$qb->andwhere('f.tags LIKE :tags');
				$qb->setParameter('tags', '%'.$tag.'%');
				$qb->andwhere('f.copyof is NULL');
				$qb->setMaxResults(50);
				$count_ta = $qb->getQuery()->getResult();
				$j = $i-1;
				$array_tags = ${'array_tags'.$j};
				${'array_tags'.$i} = array_merge($array_tags,$count_ta);				
			}
		}
	}
	if($actv != 0)
	{
		foreach($actv as $act)
		{$i++;
			if($i == 1)
			{
				$qb = $this->createQueryBuilder('f');
				$qb->where('f.user != :user')
					->setParameters(array('user' => $user, 'user' => 'x'));	
			$qb->andwhere('f.copyof is NULL');
			$qb->andWhere('f.usersociete is NULL');
				$qb->andwhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$act.'%');
				$qb->setMaxResults(50);
				$count_ta = $qb->getQuery()->getResult();
				${'array_tags'.$i} = $count_ta;
			}
			else
			{		
				$qb = $this->createQueryBuilder('f');
				$qb->where('f.user != :user')
					->setParameters(array('user' => $user, 'user' => 'x'));	
			$qb->andwhere('f.copyof is NULL');
			$qb->andWhere('f.usersociete is NULL');
				$qb->andwhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$act.'%');
				$qb->setMaxResults(50);
				$count_ta = $qb->getQuery()->getResult();
				$j = $i-1;
				$array_tags = ${'array_tags'.$j};
				${'array_tags'.$i} = array_merge($array_tags,$count_ta);
			}
		}
	}
		$list_fichespot = ${'array_tags'.$i};
		return $list_fichespot;
	}

	public function searchfichebacloo2($besoin, $activite, $departement, $nombreParPage, $page, $user, $mode)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		if($mode == 'prospssc')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.prixsscont > :prixsscont')
			->setParameter('prixsscont', '0');	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');			
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$qb->setFirstResult(($page-1) * $nombreParPage)
			// Ainsi que le nombre d'articles à afficher
			->setMaxResults($nombreParPage);
			// Enfin, on retourne l'objet Paginator correspondant à la requête construite
			// (n'oubliez pas le use correspondant en début de fichier)
			return new Paginator($qb);
		}
		elseif($mode == 'prospavc')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.prixavcont > :prixavcont')
			->setParameter('prixavcont', '0');	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$qb->setFirstResult(($page-1) * $nombreParPage)
			// Ainsi que le nombre d'articles à afficher
			->setMaxResults($nombreParPage);
			// Enfin, on retourne l'objet Paginator correspondant à la requête construite
			// (n'oubliez pas le use correspondant en début de fichier)
			return new Paginator($qb);
		}		
		elseif($mode == 'allprosp')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$qb->setFirstResult(($page-1) * $nombreParPage)
			// Ainsi que le nombre d'articles à afficher
			->setMaxResults($nombreParPage);
			// Enfin, on retourne l'objet Paginator correspondant à la requête construite
			// (n'oubliez pas le use correspondant en début de fichier)
			return new Paginator($qb);
		}

	}
	
	public function searchfichebacloosp($besoin, $activite, $departement, $user, $mode)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if($mode == 'prospssc')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.prixsscont > :prixsscont')
			->setParameter('prixsscont', '0');	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$nbfiche = $qb->getQuery()->getResult();
			return $nbfiche;
		}
		elseif($mode == 'prospavc')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.prixavcont > :prixavcont')
			->setParameter('prixavcont', '0');	
			$qb->andwhere('f.user != :user');
			$qb->andWhere('f.usersociete is NULL');
			$qb->setParameter('user', $user);			
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$nbfiche = $qb->getQuery()->getResult();
			return $nbfiche;
		}		
		elseif($mode == 'allprosp')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');			
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$nbfiche = $qb->getQuery()->getResult();
			return $nbfiche;
		}	
	}
	
	public function searchpremfichebacloo($besoin, $activite, $departement, $nombreParPage, $page, $user, $mode)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		if($mode == 'prospssc')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.prixsscont > :prixsscont')
			->setParameter('prixsscont', '0');	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$prems = $qb->getQuery()->setFirstResult(($page-1) * $nombreParPage)->getScalarResult();
			
			return $prems;
		}
		elseif($mode == 'prospavc')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.prixavcont > :prixavcont')
			->setParameter('prixavcont', '0');	
			$qb->andwhere('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$qb->setFirstResult(($page-1) * $nombreParPage)
			// Ainsi que le nombre d'articles à afficher
			->setMaxResults($nombreParPage);
			// Enfin, on retourne l'objet Paginator correspondant à la requête construite
			// (n'oubliez pas le use correspondant en début de fichier)
			return new Paginator($qb);
		}		
		elseif($mode == 'allprosp')
		{
			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user != :user');
			$qb->setParameter('user', $user);
			$qb->andWhere('f.usersociete is NULL');
			if(isset($activite)){
				$qb->andWhere('f.activite LIKE :activite');
				$qb->setParameter('activite', '%'.$activite.'%');
			}	

			if(isset($besoin))
			{
				$qb->andWhere('f.tags LIKE :tags')
				->setParameter('tags', '%'.$besoin.'%');			
			}		
			
			if(isset($departement)){
				$qb->andWhere('f.cp LIKE :cp');
				$qb->setParameter('cp', $departement.'%');	
			}			
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$qb->setFirstResult(($page-1) * $nombreParPage)
			// Ainsi que le nombre d'articles à afficher
			->setMaxResults($nombreParPage);
			// Enfin, on retourne l'objet Paginator correspondant à la requête construite
			// (n'oubliez pas le use correspondant en début de fichier)
			return new Paginator($qb);
		}

	}	
	
    public function getUserlist($username)
    {
		$qb = $this->createQueryBuilder('f');
         
        $qb->where('f.userid = :userid')
              ->setParameter('userid', $id);
                 
        return $qb->getQuery()->getResult();
    }	

    public function createpiplinearray(array $user)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'p')
				   ->addSelect('p');
         
        $qb->where('f.user in (:user)')
              ->setParameter('user', $user)
		   ->andWhere('p.pipeorder > :pipeorder')
		   ->setParameter('pipeorder', 0);
                 
        return $qb->getQuery()->getResult();
    }	
	
    public function createpipline($user)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'p')
				   ->addSelect('p');
         
        $qb->where('f.user = :user')
              ->setParameter('user', $user)
		   ->andWhere('p.pipeorder > :pipeorder')
		   ->setParameter('pipeorder', 0);
                 
        return $qb->getQuery()->getResult();
    }	
	
    public function last30event($user, $today, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.event', 'e')
				   ->addSelect('e');
        $qb->select('DISTINCT COUNT(e.id) as nbevent', 'e.eventDate'); 
        $qb->where('e.user = :user')
              ->setParameter('user', $user)
		   ->andWhere('e.eventDate <= :today')
		   ->andWhere('e.eventDate > :prev30')
		   ->andWhere('e.eventComment is not null')
		   ->setParameter('today', $today)
		   ->setParameter('prev30', $prev30)
		   ->groupBy('e.eventDate');
                 
        return $qb->getQuery()->getArrayResult();
    }	
	
    public function last30eventarray($user, $today, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.event', 'e')
				   ->addSelect('e');
        $qb->select('DISTINCT COUNT(e.id) as nbevent', 'e.eventDate'); 
        $qb->where('f.user in (:user)')
              ->setParameter('user', $user)
		   ->andWhere('e.eventDate <= :today')
		   ->andWhere('e.eventDate > :prev30')
		   ->setParameter('today', $today)
		   ->setParameter('prev30', $prev30)
		   ->groupBy('e.eventDate');
                 
        return $qb->getQuery()->getArrayResult();
    }	
	
    public function before30capot($user, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'e')
				   ->addSelect('e');
        $qb->select('SUM(f.potentiel) as capotb'); 
        $qb->where('f.user = :user')
              ->setParameter('user', $user)
		   ->andWhere('f.lastmodif < :prev30')
		   ->andWhere('e.perdu != :perdu')
		   ->andWhere('e.exclusion != :exclusion')
		   ->setParameter('prev30', $prev30)
		   ->setParameter('perdu', 1)
		   ->setParameter('exclusion', 1);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }	
	
    public function before30capotarray($user, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'e')
				   ->addSelect('e');
        $qb->select('SUM(f.potentiel) as capotb'); 
        $qb->where('f.user in (:user)')
              ->setParameter('user', $user)
		   ->andWhere('f.lastmodif < :prev30')
		   ->andWhere('e.perdu != :perdu')
		   ->andWhere('e.exclusion != :exclusion')
		   ->setParameter('prev30', $prev30)
		   ->setParameter('perdu', 1)
		   ->setParameter('exclusion', 1);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }	
	
    public function before30careal($user, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'e')
				   ->addSelect('e');
        $qb->select('SUM(f.potentiel) as capotb'); 
        $qb->where('f.user = :user')
              ->setParameter('user', $user)
		   ->andWhere('f.lastmodif < :prev30')
		   ->andWhere('e.realise = :realise')
		   ->setParameter('prev30', $prev30)
		   ->setParameter('realise', 1);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }		
	
    public function before30carealarray($user, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'e')
				   ->addSelect('e');
        $qb->select('SUM(f.potentiel) as capotb'); 
        $qb->where('f.user in (:user)')
              ->setParameter('user', $user)
		   ->andWhere('f.lastmodif < :prev30')
		   ->andWhere('e.realise = :realise')
		   ->setParameter('prev30', $prev30)
		   ->setParameter('realise', 1);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }	
	
    public function before30caperdu($user, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'e')
				   ->addSelect('e');
        $qb->select('SUM(f.potentiel) as capotb'); 
        $qb->where('f.user = :user')
              ->setParameter('user', $user)
		   ->andWhere('f.lastmodif < :prev30')
		   ->andWhere('e.perdu = :perdu')
		   ->setParameter('prev30', $prev30)
		   ->setParameter('perdu', 1);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }	
	
    public function before30caperduarray($user, $prev30)
    {
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.Pipeline', 'e')
				   ->addSelect('e');
        $qb->select('SUM(f.potentiel) as capotb'); 
        $qb->where('f.user in (:user)')
              ->setParameter('user', $user)
		   ->andWhere('f.lastmodif < :prev30')
		   ->andWhere('e.perdu = :perdu')
		   ->setParameter('prev30', $prev30)
		   ->setParameter('perdu', 1);
                 
        return $qb->getQuery()->getSingleScalarResult();
    }

	public function searchcr($du, $au, $nombreParPage, $page, $user, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.event', 'r')
					->addSelect('r');
		$qb->where('r.eventDate <= :au')
		->setParameter('au', $au)
		->andWhere('r.eventDate >= :du')
		->setParameter('du', $du);
		if($user != 'tous')
		{
			$qb->andWhere('r.user = :user')
			->setParameter('user', $user);
		}
		else
		{
			$qb->andWhere('f.usersociete = :usersociete')
			->setParameter('usersociete', $societe);
		}
		$qb->andWhere('r.cr = :cr')
		->setParameter('cr', 1)
		->orderBy('r.eventDate', 'ASC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}

	public function searchcradmin($du, $au, $nombreParPage, $page, $user, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.event', 'r')
					->addSelect('r');
		$qb->where('r.eventDate <= :au')
		->setParameter('au', $au)
		->andWhere('r.eventDate >= :du')
		->setParameter('du', $du)
		->andWhere('r.eventComment != :du')
		->setParameter('du', '');
		if($user != 'tous')
		{
			$qb->andWhere('r.user = :user')
			->setParameter('user', $user);
		}
		else
		{
			$qb->andWhere('f.usersociete = :usersociete')
			->setParameter('usersociete', $societe);
		}
		$qb->orderBy('r.eventDate', 'DESC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}

	public function searchbrappelsadmin($du, $au, $nombreParPage, $page, $user, $societe)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.brappels', 'r')
					->addSelect('r');
		$qb->where('r.date <= :au')
		->setParameter('au', $au)
		->andWhere('r.date >= :du')
		->setParameter('du', $du)
		->andWhere('r.rapTexte != :texte')
		->setParameter('texte', '');
		if($user != 'tous')
		{
			$qb->andWhere('r.user = :user')
			->setParameter('user', $user);
		}
		else
		{
			$qb->andWhere('f.usersociete = :usersociete')
			->setParameter('usersociete', $societe);
		}
		$qb->orderBy('r.date', 'DESC');	
		$qb->getQuery();

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
	
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM BaclooCrmBundle:Fiche e
                WHERE e.raisonSociale LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function updateData($data)
    {
        // $data = $request->get('input');
        
        // $em = $this->getDoctrine()->getManager();
 		$qb = $this->createQueryBuilder('f');
		$qb->where('f.raisonSociale LIKE :raisonSociale')
		->setParameter('raisonSociale','%'.$data.'%')		
		->orderBy('f.raisonSociale', 'ASC');					

           $arrayAss = $qb->getQuery()
        ->getArrayResult();
 
		// Transformer le tableau associatif en un tableau standard
		$array = array();
		foreach ($arrayAss as $data) {
			$array[] = $data['raisonSociale'];
		}
 
		return $array;
	}		
	
    public function listerelance()
    {
		$today = date('Y-m-d');
		$qb = $this->createQueryBuilder('f')
				   ->leftJoin('f.factures', 'b')
				   ->addSelect('b');
		$qb->where('b.echeance = :daterelance')
		->setParameter('daterelance', $today)
        ->orderBy('b.echeance', 'ASC');	
                 
        return $qb->getQuery()->getResult();
    }
}