<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichesvendablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichesvendablesRepository extends EntityRepository
{
		
}
