<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * interressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class interressesRepository extends EntityRepository
{
	public function listintfiche($id)
	{
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.ficheid = :ficheid')
				->setParameter('ficheid', $id);	
			return $listintfiche = $qb->getQuery()->getResult();
	}

}
