<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocataventescloneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocataventescloneRepository extends \Doctrine\ORM\EntityRepository
{
}
