<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocationsfrscloneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsfrscloneRepository extends \Doctrine\ORM\EntityRepository
{
}
