<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocatafrscloneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatafrscloneRepository extends \Doctrine\ORM\EntityRepository
{
}
