<?php

namespace Bacloo\CrmBundle\Entity;
use DoctrineExtensions\Query\Mysql\Month;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LocatafrsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatafrsRepository extends \Doctrine\ORM\EntityRepository
{
	public function achatsafacturer($debutmois, $finmois)
	{
		$today = date('Y-m-01', strtotime(" -1 month"));
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationsfrs', 'v')
					->addSelect('v');
		// $qb->where('c.etatloc = :etatloc and s.etatloc = :etatloc')
		$qb->where('f.etatbdc = :etatbdc')
		->setParameter('etatbdc', 1)
		->andWhere('(f.datemodif >= :today) or (v.finloc >= :today) or (v.debutloc <= :finmois and v.finloc >= :debutmois) or (v.debutloc <= :finmois2 and v.finloc >= :debutmois2 and v.aechoir = :mode)')
		->setParameter('finmois', $finmois)
		->setParameter('debutmois', $debutmois)
		->setParameter('finmois2', date('Y-m-d', strtotime($finmois . ' +1 month')))
		->setParameter('debutmois2', date('Y-m-d', strtotime($debutmois . ' +1 month')))
		->setParameter('mode', 1)
		->setParameter('today', $today)
		->andWhere('f.codelocatasl = :codelocatasl or f.codelocatasl is null')
		->setParameter('codelocatasl', '')
		->andWhere('v.cloture = :cloture')
		->setParameter('cloture', 0)
		->groupBy('f.id');
		return $qb->getQuery()->getScalarResult();
	}
	
	public function isbdc($condelocationsl)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationsfrs', 'v')
					->addSelect('v');
		// $qb->where('c.etatloc = :etatloc and s.etatloc = :etatloc')	
		$qb->where('v.codelocationsl = :codelocationsl')	
		->setParameter('codelocationsl', $codelocationsl);					
		return $qb->getQuery()->getScalarResult();
	}
	
    public function statachats($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.montantloc) as careal, YEARMONTH(c.datemodif) as datemodif'); 
        $qb->where('c.etatbdc = :etatbdc')
              ->setParameter('etatbdc', 1)
		   ->andWhere('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->groupBy('datemodif')
		   ->orderBy('datemodif');
                 
        return $qb->getQuery()->getArrayResult();
    }

    public function cafrs($debutmois, $finmois)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.locationsfrs', 'v')
            ->addSelect('v');
        // $qb->where('c.etatloc = :etatloc and s.etatloc = :etatloc')
        $qb->Where('(v.debutloc <= :finmois and v.debutloc  >= :debutmois)')
            ->setParameter('finmois', $finmois)
            ->setParameter('debutmois', $debutmois)
            ->andWhere('v.codelocationsl > :codelocationsl or v.codelocationsl is not null')
            ->setParameter('codelocationsl', 0)
            ->andWhere('v.montantht > :montantloc')
            ->setParameter('montantloc', 0);
        return $qb->getQuery()->getResult();
    }

    public function cafrsdetaille($mois, $fournisseur)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.locationsfrs', 'v')
            ->addSelect('v');
        // $qb->where('c.etatloc = :etatloc and s.etatloc = :etatloc')
        $qb->Where('YEARMONTH(v.debutloc) = :mois')
            ->setParameter('mois', $mois)
            ->andWhere('v.codelocationsl > :codelocationsl or v.codelocationsl is not null')
            ->setParameter('codelocationsl', 0)
            ->andWhere('v.montantht > :montantloc')
            ->setParameter('montantloc', 0)
            ->andWhere('v.fournisseur = :fournisseur')
            ->setParameter('fournisseur', $fournisseur);
        return $qb->getQuery()->getResult();
    }

    public function camensuelarrayclient($search, $nombreParPage, $page, $dStart, $dEnd, $client)
    {
        // On déplace la vérification du numéro de page dans cette méthode
        if ($page < 1) {

        }
        // On utilise le QueryBuilder créé par le repository directement pour gagner du temps
        // Plus besoin de faire le select() ni le from() par la suite donc
        if($search == 0)
        {//echo 'ici';
            $qb = $this->createQueryBuilder('a');
            $qb->where('YEARMONTH(a.datemodif) <= :today')
                ->setParameter('today', date('Ym',strtotime($dEnd)))
                ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
                ->setParameter('dtsart', date('Ym',strtotime($dStart)))
                ->groupBy('a.fournisseur')
                ->orderBy('a.fournisseur', 'ASC');
            $qb->getQuery();
        }
        else
        {//echo 'la'.$client;
            $qb = $this->createQueryBuilder('a');
            $qb->where('YEARMONTH(a.datemodif) <= :today')
                ->setParameter('today', date('Ym',strtotime($dEnd)))
                ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
                ->setParameter('dtsart', date('Ym',strtotime($dStart)));
            if($client !== 0)
            {//echo 'client';
                $qb->andWhere('(a.fournisseur) = :fournisseur')
                    ->setParameter('fournisseur', $client);
            }
            $qb->groupBy('a.fournisseur');
            $qb->orderBy('a.fournisseur', 'ASC');
            $qb->getQuery();
        }

        // On définit l'article à partir duquel commencer la liste
        $qb->setFirstResult(($page-1) * $nombreParPage)
            // Ainsi que le nombre d'articles à afficher
            ->setMaxResults($nombreParPage);
        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($qb);
    }

    public function camensuelarrayclienttotal($dStart, $dEnd, $search, $client)
    {
        if($search == 0)
        {//echo 'ici';
            // On utilise le QueryBuilder créé par le repository directement pour gagner du temps
            // Plus besoin de faire le select() ni le from() par la suite donc
            $qb = $this->createQueryBuilder('a');
            $qb->where('YEARMONTH(a.datemodif) <= :today')
                ->setParameter('today', date('Ym',strtotime($dEnd)))
                ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
                ->setParameter('dtsart', date('Ym',strtotime($dStart)))
                ->groupBy('a.fournisseur')
                ->orderBy('a.datemodif');
        }
        else
        {
            $qb = $this->createQueryBuilder('a');
            $qb->where('YEARMONTH(a.datemodif) <= :today')
                ->setParameter('today', date('Ym',strtotime($dEnd)))
                ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
                ->setParameter('dtsart', date('Ym',strtotime($dStart)));
            if($client != 0)
            {
                $qb->andWhere('(a.fournisseur) = :fournisseur')
                    ->setParameter('fournisseur', $client);
            }
            $qb->orderBy('a.fournisseur', 'ASC');
        }
        return $qb->getQuery()->getResult();
    }

    public function trouverBdcauto($codecontrat, $loueurid)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.locationsfrs', 'v')
            ->addSelect('v');
        // $qb->where('c.etatloc = :etatloc and s.etatloc = :etatloc')
        $qb->where('f.codelocatasl = :codelocatasl')
            ->setParameter('codelocatasl', $codecontrat)
            ->andWhere('v.fournisseurid = :loueurid')
            ->setParameter('loueurid', $loueurid);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
