<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsRepository extends \Doctrine\ORM\EntityRepository
{
	public function nblocparc()
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('COUNT(f.id) as nblocparc');
		$qb->where('f.etatloc = :etatloc')
			->setParameter('etatloc', 'En location');
		$nblocparc = $qb->getQuery()->getSingleScalarResult();

		return $nblocparc;
	}
}
