<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocationsfrsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsfrsRepository extends \Doctrine\ORM\EntityRepository
{
}
