<?php

namespace Bacloo\CrmBundle\Entity;
/**
 * LocataslRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocataslRepository extends \Doctrine\ORM\EntityRepository
{
	public function adispatcher($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.debutloc = :debutloc')
		->setParameter('debutloc', $date)		
		->andWhere('f.contrat = :contrat')		
		->setParameter('contrat', 1)		
		->andWhere("c.codemachineinterne = '' OR c.codemachineinterne is NULL")
		->orderBy('c.codemachine', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function resa($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.debutloc = :debutloc')
		->setParameter('debutloc', $date)		
		->andWhere('f.bdcrecu = :bdcrecu')		
		->setParameter('bdcrecu', 1)		
		->andWhere('c.etatloc = :etatloc')		
		->setParameter('etatloc', 'Réservé')
		->orderBy('c.codemachine', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function apreprarer($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.datereprise <= :datereprise')
		->setParameter('datereprise', $date)		
		->andWhere('f.contrat = :contrat')		
		->setParameter('contrat', 1)
		->andwhere('c.etatloc = :etatloc')
		->setParameter('etatloc', 'Retour planifié')			
		->orderBy('c.finloc', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function dejadispatch($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.debutloc = :debutloc')
		->setParameter('debutloc', $date)
		->andWhere('c.etatloc = :etatloc')
		->setParameter('etatloc', 'Prêt au départ')	
		->andWhere('c.etatloc = :etatloca')
		->setParameter('etatloca', 'En location')		
		->orderBy('c.codemachine', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function machinespretes($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.debutloc = :debutloc')
		->setParameter('debutloc', $date)		
		->andWhere('f.contrat = :contrat')		
		->setParameter('contrat', 1)		
		->andWhere("c.codemachineinterne != ''")		
		->orderBy('c.codemachine', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function retours($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.finloc <= :finloc')
		->setParameter('finloc', $date)		
		->andWhere('f.contrat = :contrat')	
		->setParameter('contrat', 1)
		->andwhere('c.etatloc != :etatloc')
		->setParameter('etatloc', 'Retour planifié')
		->andwhere('c.etatloc != :etatloca')
		->setParameter('etatloca', 'Annulée')					
		->orderBy('c.finloc', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function livraisons($date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.debutloc <= :debutloc')
		->setParameter('debutloc', $date)		
		->andWhere('f.contrat = :contrat')	
		->setParameter('contrat', 1)
		->andwhere('c.etatloc = :etatloc')
		->setParameter('etatloc', 'Prêt au départ')					
		->orderBy('c.debutloc', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function findByEtatloc($etatloc)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.etatloc = :etatloc')
		->setParameter('etatloc', $etatloc)				
		->orderBy('c.codemachineinterne', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function findByEtatloca($etatloc, $date)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.etatloc = :etatloc')
		->setParameter('etatloc', $etatloc)				
		->andWhere('c.debutloc = :debutloc')				
		->setParameter('debutloc', $date)				
		->orderBy('c.codemachineinterne', 'ASC');				
		return $qb->getQuery()->getResult();
	}
	
	public function last5loc($codemachine)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.codemachineinterne = :codemachineinterne')
		->setParameter('codemachineinterne', $codemachine)
		->orderBy('c.id', 'DESC')
		->setMaxResults(6);						
		$last5loc = $qb->getQuery()->getResult();
		return $last5loc;
	}
	
	public function findByEtatlog($etatlog)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationssl', 'c')
					->addSelect('c');
		$qb->where('c.etatlog = :etatlog')
		->setParameter('etatlog', $etatlog)				
		->orderBy('c.codemachineinterne', 'ASC');					
		return $qb->getQuery()->getResult();
	}
	
	public function devisnonvadsl()
	{
		$qb = $this->createQueryBuilder('f');
		$qb->where('f.offreencours = :offreencours')
		->setParameter('offreencours', 1)
		->andWhere('f.bdcrecu = :bdcrecu')
		->setParameter('bdcrecu', 0)
		->andWhere('f.contrat = :contrat')
		->setParameter('contrat', 0)	
		->andWhere('f.annulee = :annulee')
		->setParameter('annulee', 0)	
		->andWhere('f.offrerefusee = :offrerefusee')
		->setParameter('offrerefusee', 0);					
		return $qb->getQuery()->getResult();
	}
}