<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocationsslcloneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsslcloneRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function camensuel($search, $dStart, $dEnd)
	{
		if($search == 0)
		{//echo 'laaaa';echo $dEnd;echo $dStart;
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->orderBy('a.codemachineinterne', 'ASC');	
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->where('a.codemachineinterne = :search')
			->setParameter('search', $search) 
			->andwhere('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->orderBy('a.codemachineinterne', 'ASC');
		}
		return $qb->getQuery()->getResult();	
	}
	
	public function camensueltype($search, $dStart, $dEnd)
	{
		if($search == 0)
		{//echo 'laaaa';echo $dEnd;echo $dStart;
			$qb = $this->createQueryBuilder('a');
			$qb->select('a.montantloc as montantloc, YEARMONTH(a.debutloc) as debutloc, a.codemachine'); 
			$qb->where('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->orderBy('a.codemachine', 'ASC');	
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->where('a.codemachine = :search')
			->setParameter('search', $search) 
			->andwhere('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->orderBy('a.codemachine', 'ASC');
		}
		return $qb->getQuery()->getResult();	
	}
	
	public function camensuelarrayclient($search, $nombreParPage, $page, $dStart, $dEnd)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($search == 0)
		{//echo 'ici';
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.codemachineinterne')
		   ->orderBy('a.codemachineinterne', 'ASC');	
			$qb->getQuery();	
		}
		else
		{//echo 'la'.$search;
			$qb = $this->createQueryBuilder('a');
			$qb->where('a.codemachineinterne = :search')
			->setParameter('search', $search) 
			->andwhere('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.codemachineinterne')
		   ->orderBy('a.debutloc');	
			$qb->getQuery();
		}

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
	
	public function camensuelarrayclienttype($search, $nombreParPage, $page, $dStart, $dEnd)
	{
		// On déplace la vérification du numéro de page dans cette méthode

		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($search == 0)
		{//echo 'ici';
			$qb = $this->createQueryBuilder('a');
			$qb->select('DISTINCT SUM(a.montantloc) as montantloc, YEARMONTH(a.debutloc) as debutloc, a.codemachine')
		   ->groupBy('a.codemachine')
		   ->orderBy('montantloc', 'DESC');
                 
        return $qb->getQuery()->getArrayResult();	
		}
		else
		{//echo 'la'.$search;
			$qb = $this->createQueryBuilder('a');
			$qb->select('DISTINCT SUM(a.montantloc) as montantloc, YEARMONTH(a.debutloc) as debutloc, a.codemachine'); 
			$qb->where('a.codemachine = :search')
			->setParameter('search', $search) 
		   ->groupBy('a.codemachine')
		   ->orderBy('montantloc', 'DESC');
                 
        return $qb->getQuery()->getArrayResult();
		}
	}
	
	public function camensuelarrayclienttotal($dStart, $dEnd)
	{

		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.codemachineinterne')
		   ->orderBy('a.debutloc');

		return $qb->getQuery()->getResult();	
	}
	
	public function camensuelarraycodemachine($dStart, $dEnd)
	{

		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.debutloc) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.debutloc) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.codemachine')
		   ->orderBy('a.debutloc');

		return $qb->getQuery()->getResult();	
	}
}
