<?php

namespace Bacloo\CrmBundle\Entity;
use DoctrineExtensions\Query\Mysql\Month;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LocatacloneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatacloneRepository extends \Doctrine\ORM\EntityRepository
{	
	public function statloccarb($dStart, $dEnd)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationsclone', 'c')
					->leftJoin('f.locationsslclone', 's')
					->addSelect('c');
		$qb->where('c.debutloc <= :debutloc and c.finloc >= :finloc')
		->setParameter('debutloc', $dEnd)
		->setParameter('finloc', $dStart)
		->orWhere('s.debutloc <= :debutloco and s.finloc >= :finloco')
		->setParameter('debutloco', $dEnd)
		->setParameter('finloco', $dStart)		
		->andWhere('f.contrat = :contrat')		
		->setParameter('contrat', 1);
		   // ->andWhere('f.client = :client')
		   // ->setParameter('client', 'GREENCABLE');						
		$statloc = $qb->getQuery()->getResult();

		return $statloc;
	}
	
	public function statloc($dStart, $dEnd)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationsclone', 'c')
					->leftJoin('f.locationsslclone', 's')
					->addSelect('c')
					->addSelect('s');
		$qb->where('c.finloc >= :finloc')
		->setParameter('finloc', $dStart)
		->orWhere('s.finloc >= :finloco')
		->setParameter('finloco', $dStart)		
		->andWhere('f.contrat = :contrat')		
		->setParameter('contrat', 1);
		   // ->andWhere('f.client = :client')
		   // ->setParameter('client', 'GREENCABLE');					
		$statloc = $qb->getQuery()->getResult();

		return $statloc;
	}
	
	public function statlocmois($dStart, $dEnd)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.locationsclone', 'c')
					->leftJoin('f.locationsslclone', 's')
					->addSelect('c')
					->addSelect('s');
		$qb->where('c.debutloc <= :finloc and c.finloc >= :debutloc')
		->setParameter('debutloc', $dStart)
		->setParameter('finloc', $dEnd)
		->orWhere('s.debutloc <= :finloco and s.finloc >= :debutloco')
		->setParameter('debutloco', $dStart)
		->setParameter('finloco', $dEnd)		
		->andWhere('f.contrat = :contrat')		
		->setParameter('contrat', 1);
		   // ->andWhere('f.client = :client')
		   // ->setParameter('client', 'GREENCABLE');					
		$statlocmois = $qb->getQuery()->getResult();

		return $statlocmois;
	}	
	
	public function caolocmensuelle()
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('SUM(f.montantloc)');
		$qb->groupBy('MONTH(f.datemodif)');		
		$caolocmensuelle = $qb->getQuery()->getResult();
		return $caolocmensuelle;
	}	
	
	public function caotransportmensuelle()
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('SUM(f.transportaller)+SUM(f.transportretour)');
		$qb->groupBy('MONTH(f.datemodif)');		
		$caotransportmensuelle = $qb->getQuery()->getResult();
		return $caotransportmensuelle;
	}	
	
	public function caoffres($du, $user)
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('SUM(f.montantloc)+SUM(f.transportaller)+SUM(f.transportretour)+SUM(f.assurance)+SUM(f.contributionverte)');
		$qb->where('f.user = :user')
		->setParameter('user', $user)
		->andwhere('f.offreencours = :nb')
		->setParameter('nb', 1)		
		->andWhere('f.datemodif >= :du')
		->setParameter('du', $du);					
		$caoffres = $qb->getQuery()->getSingleScalarResult();

		return $caoffres;
	}

    public function caloc($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.montantloc) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   // ->andWhere('c.client = :client')
		   // ->setParameter('client', 'GREENCABLE')
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }	

    public function catransport($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.transportaller)+SUM(c.transportretour) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }		

    public function caassurance($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.assurance) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }		

    public function cacontributionverte($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.contributionverte) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }		

    public function cacarburant($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.montantcarb) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }	

    public function calocavente($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.montantlocavente) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }
	
    public function last12mca3($dStart, $dEnd)//Pour calculer le CA du mois
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('(SUM(c.montantloc)+SUM(c.assurance)+SUM(c.contributionverte)+SUM(c.transportaller)+SUM(c.transportretour)+SUM(c.montantcarb)+SUM(c.montantlocavente)) as careal, c.user, YEARMONTH(c.datemodif) as datecrea'); 
        $qb->where('YEARMONTH(c.datemodif) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.datemodif) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }
	
	public function camensuelold($search, $nombreParPage, $page, $dStart, $dEnd)
	{
		// On d�place la v�rification du num�ro de page dans cette m�thode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder cr�� par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($search === 0)
		{
			$qb = $this->createQueryBuilder('a');
			$qb->select('(SUM(a.montantloc)+SUM(a.assurance)+SUM(a.contributionverte)+SUM(a.transportaller)+SUM(a.transportretour)+SUM(a.montantcarb)+SUM(a.montantlocavente)) as careal, a.user, YEARMONTH(a.datemodif) as datecrea');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.client')
		   ->addgroupBy('datecrea')
		   ->orderBy('datecrea');	
			$qb->getQuery();	
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->select('(SUM(a.montantloc)+SUM(a.assurance)+SUM(a.contributionverte)+SUM(a.transportaller)+SUM(a.transportretour)+SUM(a.montantcarb)+SUM(a.montantlocavente)) as careal, a.user, YEARMONTH(a.datemodif) as datecrea');
			$qb->where('a.client = :search')
			->setParameter('search', $search) 
			->andwhere('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.client')
		   ->addgroupBy('datecrea')
		   ->orderBy('datecrea');	
			$qb->getQuery();
		}

		// On d�finit l'article � partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles � afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant � la requ�te construite
		// (n'oubliez pas le use correspondant en d�but de fichier)
		return new Paginator($qb);		
	}
	
	public function camensuel($search, $dStart, $dEnd, $client)
	{
		if($search == 0)
		{//echo 'laaaa';echo $dEnd;echo $dStart;
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->orderBy('a.client', 'ASC');	
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)));
			if($client != 0)
			{
				$qb->andWhere('(a.client) = :client')
				->setParameter('client', $client);
			}
		   $qb->orderBy('a.client', 'ASC');
		}
		return $qb->getQuery()->getResult();	
	}
	
	public function camensueldet($search, $dStart, $dEnd, $client)
	{
		if($search == 0)
		{//echo 'laaaa';echo $dEnd;echo $dStart;
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))	
		   ->orderBy('a.client', 'ASC');	
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)));
			if($client != 0)
			{
				$qb->andWhere('(a.client) = :client')
				->setParameter('client', $client);
			}
		   $qb->orderBy('a.client', 'ASC');
		}
		return $qb->getQuery()->getResult();	
	}
	
	public function camensuelarrayclient($search, $nombreParPage, $page, $dStart, $dEnd, $client)
	{
		// On d�place la v�rification du num�ro de page dans cette m�thode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder cr�� par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($search == 0)
		{//echo 'ici';
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.client')
		   ->orderBy('a.client', 'ASC');	
			$qb->getQuery();	
		}
		else
		{//echo 'la'.$client;
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)));
			if($client !== 0)
			{//echo 'client';
				$qb->andWhere('(a.client) = :client')
				->setParameter('client', $client);
			}
			$qb->groupBy('a.client');
		    $qb->orderBy('a.client', 'ASC');	
			$qb->getQuery();
		}

		// On d�finit l'article � partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles � afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant � la requ�te construite
		// (n'oubliez pas le use correspondant en d�but de fichier)
		return new Paginator($qb);		
	}
	
	public function camensuelarrayclientdet($search, $nombreParPage, $page, $dStart, $dEnd, $client)
	{
		// On d�place la v�rification du num�ro de page dans cette m�thode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder cr�� par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($search == 0)
		{//echo 'ici';
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.client')
		   ->orderBy('a.client', 'ASC');	
			$qb->getQuery();	
		}
		else
		{//echo 'la'.$client;
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)));
			if($client !== 0)
			{//echo 'client';
				$qb->andWhere('(a.client) = :client')
				->setParameter('client', $client);
			}
			$qb->groupBy('a.client');
		    $qb->orderBy('a.client', 'ASC');	
			$qb->getQuery();
		}

		// On d�finit l'article � partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles � afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant � la requ�te construite
		// (n'oubliez pas le use correspondant en d�but de fichier)
		return new Paginator($qb);		
	}
	
	public function camensuelarrayclienttotal($dStart, $dEnd, $search, $client)
	{
		if($search == 0)
		{//echo 'ici';
			// On utilise le QueryBuilder cr�� par le repository directement pour gagner du temps
			// Plus besoin de faire le select() ni le from() par la suite donc
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
			->setParameter('today', date('Ym',strtotime($dEnd)))
			->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
			->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.client')
		   ->orderBy('a.datemodif');
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)));
			if($client != 0)
			{
				$qb->andWhere('(a.client) = :client')
				->setParameter('client', $client);
			}
		   $qb->orderBy('a.client', 'ASC');
		}
		return $qb->getQuery()->getResult();	
	}
	
	public function camensuelarrayclienttotaldet($dStart, $dEnd, $search, $client)
	{
		if($search == 0)
		{//echo 'ici';
			// On utilise le QueryBuilder cr�� par le repository directement pour gagner du temps
			// Plus besoin de faire le select() ni le from() par la suite donc
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
			->setParameter('today', date('Ym',strtotime($dEnd)))
			->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
			->setParameter('dtsart', date('Ym',strtotime($dStart)))
		   ->groupBy('a.client')
		   ->orderBy('a.datemodif');
		}
		else
		{
			$qb = $this->createQueryBuilder('a');
			$qb->where('YEARMONTH(a.datemodif) <= :today')
		    ->setParameter('today', date('Ym',strtotime($dEnd)))
		    ->andWhere('YEARMONTH(a.datemodif) >= :dtsart')
		    ->setParameter('dtsart', date('Ym',strtotime($dStart)));
			if($client != 0)
			{
				$qb->andWhere('(a.client) = :client')
				->setParameter('client', $client);
			}
		   $qb->orderBy('a.client', 'ASC');
		}
		return $qb->getQuery()->getResult();	
	}

    public function locatacloneamodifier()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->join('BaclooCrmBundle:Factures', 'f', 'WITH', 'a.id = f.locatacloneid');
        $qb->select('a, f');
        $qb->where('a.datemodif != f.datecrea');
        $results = $qb->getQuery()->getResult();

        return $results;
    }
}
