<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LocataventesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocataventesRepository extends \Doctrine\ORM\EntityRepository
{

}
