<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LogistiquerepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogistiquerepRepository extends \Doctrine\ORM\EntityRepository
{
}
