<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LogistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogistiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
