<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LogisrepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogisrepRepository extends \Doctrine\ORM\EntityRepository
{
}
