<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * LogisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogisRepository extends \Doctrine\ORM\EntityRepository
{
}
