<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * MachinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachinesRepository extends \Doctrine\ORM\EntityRepository
{
	public function dispos($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code');
		$qb->where('m.codegenerique = :codegenerique')
		->setParameter('codegenerique', $codemachine)
            ->andwhere("(m.debutloc NOT BETWEEN :start AND :end OR m.debutloc is NULL OR m.debutloc = '') AND m.debutloc != :start AND m.debutloc != :end")
            ->andwhere("(m.finloc NOT BETWEEN :start AND :end OR m.finloc is NULL OR m.finloc = '' ) AND m.finloc != :start AND m.finloc != :end")
            ->andwhere("(m.finloc < :start AND m.debutloc < :start) OR (m.finloc > :end AND m.debutloc > :end)")
	    ->setParameter('start', $dstart)
	    ->setParameter('end', $dend)
		->andwhere("m.etat != :enpanne")
	    ->setParameter('enpanne', 'En panne')
		->groupBy('m.code');					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}
	
	public function dispoparc($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code');
		$qb->where('m.codegenerique = :codegenerique')
		->setParameter('codegenerique', $codemachine)
		->andwhere("m.etat != :enpanne")
	    ->setParameter('enpanne', 'En panne')
		->andwhere("m.etat != :loc")
	    ->setParameter('loc', 'En location')
		->andwhere("m.etat != :reserve")
	    ->setParameter('reserve', 'Réservé')
		->groupBy('m.code');					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}
	
	public function dispoprecise($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code');
		$qb->where('m.code = :code')
		->setParameter('code', $codemachine)
		->andwhere("(m.debutloc BETWEEN :start AND :end) OR (m.finloc BETWEEN :start AND :end)")
	    ->setParameter('start', $dstart)
	    ->setParameter('end', $dend);					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}
	
	public function vgpafaire()
	{
		$datevgp = date('Y-m-d', strtotime("+35 days"));
		$qb = $this->createQueryBuilder('m');
		$qb->select('m');
		$qb->where('m.prochaineVgp <= :datevgp')
		->setParameter('datevgp', $datevgp)
		->orderBy('m.prochaineVgp', 'ASC');					
		$vgpafaire = $qb->getQuery()->getResult();
		return $vgpafaire;
	}
	
	// public function dispoprecisenot($codemachine, $dstart, $dend)
	// {
		// $qb = $this->createQueryBuilder('m');
		// $qb->select('m.code');
		// $qb->where('m.code = :code')
		// ->setParameter('code', $codemachine)
		// ->andwhere("(m.debutloc NOT BETWEEN :start AND :end) OR (m.finloc NOT BETWEEN :start AND :end)")
	    // ->setParameter('start', $dstart)
	    // ->setParameter('end', $dend);					
		// $dispos = $qb->getQuery()->getResult();
		// return $dispos;
	// }
	
	public function dispoprecisenot($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code');
		$qb->where('m.code = :code')
		->setParameter('code', $codemachine)
		->andwhere("m.debutloc NOT BETWEEN :start AND :end OR m.debutloc is NULL OR m.debutloc = ''")
		->andwhere("m.finloc NOT BETWEEN :start AND :end OR m.finloc is NULL OR m.finloc = ''")
        ->andwhere("(m.debutloc <=:start AND m.finloc <=:start) OR (m.debutloc >=:end AND m.finloc >=:end)")
	    ->setParameter('start', $dstart)
	    ->setParameter('end', $dend);					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}
	
	public function dispoprecisenotresa($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code');
		$qb->where('m.code = :code')
		->setParameter('code', $codemachine)
		->andwhere("m.etat = :etat")
		->setParameter('etat', 'Réservé')
		->andwhere("m.debutloc NOT BETWEEN :start AND :end OR m.debutloc is NULL OR m.debutloc = ''")
		->andwhere("m.finloc NOT BETWEEN :start AND :end OR m.finloc is NULL OR m.finloc = ''")
        ->andwhere("(m.debutloc <=:start AND m.finloc <=:start) OR (m.debutloc >=:end AND m.finloc >=:end)")
	    ->setParameter('start', $dstart)
	    ->setParameter('end', $dend);					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}
	
	public function dispopreciseresa($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code');
		$qb->where('m.code = :code')
		->setParameter('code', $codemachine)
		->andwhere("m.etat = :etat")
		->setParameter('etat', 'Réservé')
		->andwhere("m.debutloc BETWEEN :start AND :end AND m.debutloc is not NULL AND m.debutloc != ''")
		->andwhere("m.finloc BETWEEN :start AND :end AND m.finloc is NULL AND m.finloc != ''")
		->orwhere("m.debutloc <= :start  AND m.finloc >= :end")
	    ->setParameter('start', $dstart)
	    ->setParameter('end', $dend);					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}
	
	public function unedispo($codemachine, $dstart, $dend)
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.code, m.etat, m.energie, m.id');
		$qb->where('m.codegenerique = :codegenerique')
		->setParameter('codegenerique', $codemachine)
		->andwhere("m.debutloc NOT BETWEEN :start AND :end OR m.debutloc is NULL OR m.debutloc = ''")
		// ->andwhere("m.debutloc != :start")
		// ->andwhere("m.original = :original OR m.original =:original1")
		// ->andwhere("m.debutloc NOT BETWEEN :start AND :end OR m.debutloc is NULL OR m.debutloc = '' OR m.etat = 'Réservé'")//Pas sûr qu'il faille mettre le filtre etat
	    // ->setParameter('start', $dstart)
	    // ->setParameter('end', $dend)
		->andwhere("m.finloc NOT BETWEEN :start AND :end OR m.finloc is NULL OR m.finloc = ''")
        ->andwhere("(m.debutloc <=:start AND m.finloc <=:start) OR (m.debutloc >=:end AND m.finloc >=:end)")
		// ->andwhere("m.finloc != :end")
		// ->andwhere("m.finloc NOT BETWEEN :start AND :end OR m.finloc is NULL OR m.finloc = '' OR m.etat = :etat")//Pas sûr qu'il faille mettre le filtre etat
	    ->setParameter('start', $dstart)
	    ->setParameter('end', $dend);
//		->andwhere("m.etat != :enpanne")
//	    ->setParameter('enpanne', 'En panne')
//		->andwhere("m.etat != :depart")
//	    ->setParameter('depart', 'Prêt au départ')
//		->andwhere("m.etat != :retour")
//	    ->setParameter('retour', 'Retour planifié');
	    // ->setParameter('original', 1)					
	    // ->setParameter('original1', 0);					
		$dispos = $qb->getQuery()->getResult();
		return $dispos;
	}

    public function findAll()
    {	
        return $this->findBy(array(), array('code' => 'ASC'));
    }
	
	public function totalparc()
	{
		$qb = $this->createQueryBuilder('f');
		$qb->select('COUNT(f.id) as totalparc');
		$qb->where('f.original = :original')
			->setParameter('original', 1);
		$totalparc = $qb->getQuery()->getSingleScalarResult();

		return $totalparc;
	}
	
	public function gamme()
	{
		$qb = $this->createQueryBuilder('m');
		$qb->select('m.codegenerique');
		$qb->where('m.original = :original')
		->setParameter('original', 1)					
	    ->groupBy('m.codegenerique')		
		->orderBy('m.codegenerique', 'ASC');					
		$gamme = $qb->getQuery()->getScalarResult();
		return $gamme;
	}

	public function listemachines()
	{
		$qb = $this->createQueryBuilder('m');
		$qb->where('m.codegenerique != :codegenerique')
		->setParameter('codegenerique', 'operateur');
        $qb->andWhere('m.etat != :etat1 and m.etat != :etat2 and m.etat != :etat3 and m.etat != :etat4 and m.etat != :etat5 ')
        ->setParameter('etat1', 'Hors Usage')
        ->setParameter('etat2', 'Indisponible')
        ->setParameter('etat3', 'Pièce')
        ->setParameter('etat4', 'Vendu')
        ->setParameter('etat5', 'Volé')
		->orderBy('m.codegenerique', 'ASC');
        return $qb->getQuery()->getResult();
	}

	public function listemachines2()
	{
		$qb = $this->createQueryBuilder('m');
		$qb->where('m.codegenerique != :codegenerique')
		->setParameter('codegenerique', 'operateur');
        $qb->andWhere('m.etat != :etat1 and m.etat != :etat2 and m.etat != :etat3 and m.etat != :etat4 and m.etat != :etat5 ')
        ->setParameter('etat1', 'Hors Usage')
        ->setParameter('etat2', 'Indisponible')
        ->setParameter('etat3', 'Pièce')
        ->setParameter('etat4', 'Vendu')
        ->setParameter('etat5', 'Volé')
		->orderBy('m.code', 'ASC');
        return $qb->getQuery()->getResult();
	}

	public function listeoperateurs()
	{
		$qb = $this->createQueryBuilder('m');
		$qb->where('m.codegenerique = :codegenerique')
		->setParameter('codegenerique', 'operateur')
		->orderBy('m.codegenerique', 'ASC');
        return $qb->getQuery()->getResult();
	}
}