<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * ModaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModaRepository extends \Doctrine\ORM\EntityRepository
{
}
