<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PartenairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenairesRepository extends EntityRepository
{
	public function showpartenaires($userid, $modepart, $partenaire, $nombreParPage, $page)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {

		}	
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		if($modepart == 'partpot')
		{
			$qb = $this->createQueryBuilder('p');
			$qb->where('p.userid = :userid')
			->setParameter('userid', $userid)
			->andWhere('p.partenaire < :partenaire')
			->setParameter('partenaire', '2')
			->orderBy('p.partenaire', 'DESC');
				$qb->getQuery();		
		}
		else
		{
			$qb = $this->createQueryBuilder('p');
			$qb->where('p.userid = :userid')
			->setParameter('userid', $userid)
			->andWhere('p.partenaire = :partenaire')
			->setParameter('partenaire', $partenaire)
			->orderBy('p.userid', 'ASC');	
			$qb->getQuery();				
		}

		// On définit l'article à partir duquel commencer la liste
		$qb->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'articles à afficher
		->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($qb);		
	}
	
	public function showpartpot($id)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.userid = :userid')
		->setParameter('userid', $id)
		->andWhere('p.partenaire < :partenaire')
		->setParameter('partenaire', '2')
		->orderBy('p.partenaire', 'DESC');	
	
		return $qb->getQuery()->getResult();	
	}

	public function showpart($id)
	{
			$qb = $this->createQueryBuilder('p');
			$qb->where('p.userid = :userid')
			->setParameter('userid', $id)
			->andWhere('p.partenaire = :partenaire')
			->setParameter('partenaire', 'ok');		
	
		return $partena = $qb->getQuery()->getResult();	
	}
	
	public function trouvepart2($userid, $partid)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.userid = :userid')
		->setParameter('userid', $userid)
		->andWhere('p.partpotid = :partpotid')
		->setParameter('partpotid', $partid);	
	
		return $qb->getQuery()->getResult();	
	}
	
	public function showpartenaires_attente($userid)
	{

		$qb = $this->createQueryBuilder('p');
		$qb->where('p.partpotid = :partpotid')
		->setParameter('partpotid', $userid)
		->andWhere('p.partenaire = :partenaire')
		->setParameter('partenaire', '1')
		->orderBy('p.partpotid', 'DESC');	
		$part_attente = $qb->getQuery()
				  ->getResult();
		
		return $part_attente;		
	}
}
