<?php

namespace Bacloo\CrmBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * PipelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelineRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllPipelineByUser($userid)
	{
		$qb = $this->createQueryBuilder('f');
         
        $qb->where('f.userid = :userid')
              ->setParameter('userid', $userid);
                 
        return $qb->getQuery()->getResult();
	}		
}
