<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProspotbaclooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspotbaclooRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchprospotbacloo2($user, $nombreParPage, $page)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}

			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user = :user');
			$qb->setParameter('user', $user);			
		
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$qb->setFirstResult(($page-1) * $nombreParPage)
			// Ainsi que le nombre d'articles à afficher
			->setMaxResults($nombreParPage);
			// Enfin, on retourne l'objet Paginator correspondant à la requête construite
			// (n'oubliez pas le use correspondant en début de fichier)
			return new Paginator($qb);
	}
	
	public function searchderprospotbacloo($user, $nombreParPage, $page)
	{
		// On déplace la vérification du numéro de page dans cette méthode
		if ($page < 1) {
		throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}

			// La construction de la requête reste inchangée
			$qb = $this->createQueryBuilder('f');
			$qb->where('f.user = :user');
			$qb->setParameter('user', $user);			
		
			$qb->getQuery();
			// On définit l'article à partir duquel commencer la liste
			$prems = $qb->getQuery()->setMaxResults($nombreParPage)->getResult();
			
			return $prems;
	}
}
