<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectsRepository extends EntityRepository
{
	public function selprospects($userid)
	{
		// Sélection des tags dans la table user
	
		// La construction de la requête
		$qb = $this->createQueryBuilder('p')
					->leftJoin('p.prospot', 'c')
					->addSelect('c');		
		$qb->where('p.userid = :userid')
		->setParameter('userid', $userid)
		->andWhere('c.voir = :voir')
		->setParameter('voir', 'ok');
		
		return $qb->getQuery()
				  ->getResult();
	}
}
