<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * ReglaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglaRepository extends \Doctrine\ORM\EntityRepository
{
}
