<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * SearchuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchuserRepository extends \Doctrine\ORM\EntityRepository
{
}
