<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * TransfertsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfertsRepository extends \Doctrine\ORM\EntityRepository
{
}
