<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransacRepository extends EntityRepository
{
}
