<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * UserpipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserpipeRepository extends \Doctrine\ORM\EntityRepository
{
}
