<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * UserfavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserfavRepository extends \Doctrine\ORM\EntityRepository
{
}
