<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * VendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendaRepository extends \Doctrine\ORM\EntityRepository
{	
	public function ventesafacturer($debutmois, $finmois)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.ventes', 'v')
					->addSelect('v');
		// $qb->where('c.etatloc = :etatloc and s.etatloc = :etatloc')	
		$qb->where('f.bdcrecu = :bdcrecu')	
		->setParameter('bdcrecu', 1)	
		->andWhere('v.date <= :finmois and v.date >= :debutmois')				
		->setParameter('finmois', $finmois)				
		->setParameter('debutmois', $debutmois)			
		->groupBy('f.id');					
		return $qb->getQuery()->getScalarResult();
	}
	
	public function encoursvente($debutmois, $jodla, $id)
	{
		$qb = $this->createQueryBuilder('v');
		$qb->select('v');
		$qb->where('v.date BETWEEN :debutmois AND :jodla')
			->andWhere('v.bdcrecu = :bdcrecu')	
			->andWhere('v.clientid = :clientid')	
			->setParameter('clientid', $id)	
			->setParameter('bdcrecu', 1)
			->setParameter('debutmois',$debutmois)
			->setParameter('jodla',$jodla);
		$encoursvente = $qb->getQuery()->getResult();

		return $encoursvente;
	}
	
	public function caventejour($dStart, $dEnd)
	{
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.ventes', 'v')
					->addSelect('v');
		$qb->where('v.date <= :debutloc and v.date >= :finloc')
		->setParameter('debutloc', $dEnd)
		->setParameter('finloc', $dStart)		
		->andWhere('f.bdcrecu = :bdcrecu')		
		->setParameter('bdcrecu', 1);					
		$statloc = $qb->getQuery()->getResult();

		return $statloc;
	}	

    public function cavente($dStart, $dEnd)
    {
		$qb = $this->createQueryBuilder('c');
        $qb->select('SUM(c.montantvente) as careal, c.user, YEARMONTH(c.date) as datecrea'); 
        $qb->where('YEARMONTH(c.date) <= :today')
		   ->setParameter('today', date('Ym',strtotime($dEnd)))
		   ->andWhere('YEARMONTH(c.date) >= :dtsart')
		   ->setParameter('dtsart', date('Ym',strtotime($dStart)))
			->andWhere('c.bdcrecu = :bdcrecu')	
			->setParameter('bdcrecu', 1)
		   ->groupBy('datecrea')
		   ->orderBy('datecrea');
                 
        return $qb->getQuery()->getArrayResult();
    }

    public function ventesmachine($ecode)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.ventes', 'v')
            ->addSelect('v');
        $qb->where('v.codemachineinterne = :code')
            ->setParameter('code', $ecode)
            ->andWhere('f.bdcrecu = :bdcrecu')
            ->setParameter('bdcrecu', 1);
        $ventesmachine = $qb->getQuery()->getResult();

        return $ventesmachine;
    }
}
