<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * VentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentesRepository extends \Doctrine\ORM\EntityRepository
{
}
